title: Awesome African AI Datasets
description: Curated, free & open datasets for AI/ML focused on Africa.
theme: jekyll-theme-cayman

# Make sure GitHub Pages safe mode works
plugins: []

# Clean URLs
markdown: kramdown
kramdown:
  input: GFM

# Optional: build only the docs folder
include:
  - assets
